# -*- coding: utf-8 -*-
"""sajid_Assignment - Loops & Iterations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nqJnD_-5RSZo6htqPSZtXRaDzpANxTE7

#### The SETI Institute is a not-for-profit research organization incorporated in 1984 whose mission is to explore, understand, and explain the origin and nature of life in the universe, and to apply the knowledge gained to inspire and guide present and future generations. It aims for discovery and for sharing knowledge as scientific ambassadors to the public, the press, and the government. SETI stands for the "Search for Extraterrestrial Intelligence".

#### SETI received some signals from a far away galaxy on June 14, 2012. These signals could have been from a possible alien civilization (similar to what you would have seen in the movie Arrival).

#### The signals indicated the existence of a secret language for sending messages across. Following are the observations made by the SETI team who discovered these signals :

*   Aliens share a **tuple**, each element of tuple will be a **string** of alphabets
*   Scientists still don't know what is the content of the strings inside the tuples but depending upon the length of the string, the string translates into an alphabet (0 ≡  ,1 ≡ A, 2 ≡ B, 3 ≡ C, .., 26 ≡ Z)
*   **Space** between the words of the message is represented by an **empty string**

<br> <u>A sample message received by SETI </u><br>

**ADAM EVE** is denoted by the following tuple:

<code>
 t = ("s", "dymw", "z", "ndkjaakjkjnda","","tybhg","nmbcjbabdbsabbsbhdbshr","htroy" )</code>


Explanation:
* A list of length of each element in the tuple is : <code>[1,4,1,13,0,5,22,5]</code>
* Upon replacing numbers with corresponding alphabets and spaces, we get : 
<code>['A','D','A','M','','E','V','E'] </code>

### <u>Problem 1</u>

#### Create a dictionary where the key corresponds to the position of the alphabet(consider space as the first alphabet) and the value corresponding to the key will be the alphabet.

#### <code>range()</code> function in Python is pretty useful to get a list of numbers in sequence. You can use <code>help(range)</code> to know more about its details
"""

# Create your dictionary below with keys as position of the alphabet and the value of the key will be the alphabet itself

# Create a list of numbers from 0 to 26 using the range() function
list_of_numbers = list(range(27))
print(list_of_numbers)
for i in list_of_numbers:
# Create the list of alphabets. Hint use the split() method
  alphabets = (" ,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z")
  alphabet_list = alphabets.split()
print(alphabet_list)

# Create a dictionary by zipping together the above two lists
alphabet_dict = dict(zip(list_of_numbers, alphabets ))


# Print your dictionary to double check;
print(alphabet_dict)

zip?

"""### <u>Problem 2</u>
#### Scientists receive the following message code from the alien civilization

```
encrypyted_message = ("ajsuydtbe", "", "wunjbfusnjrgut", "uhbhr", "oirun", "lpef", "", "vhejsibr", "ydtse", "qlvuusrntuos", "ijwlbutybhlsoaxh")
```
#### You have been asked to decode the above message 
"""

# Store the message in a variable 
encrypted_message = ("ajsuydtbe", "", "wunjbfusnjrgut", "uhbhr", "oirun", "lpef", "", "vhejsibr", "ydtse", "qlvuusrntuos", "ijwlbutybhlsoaxh")

# Follow the steps from your solution to problem 1

# Create an empty list 
string_length_list  = []
# Append the length of strings of your tuple using a for loop
for i in encrypted_message:
    string_length_list= string_length_list.append(i)
print(string_length_list)


# Print the list of string lengths

len_encrypted_message= len(encrypted_message)
print(len_encrypted_message)

# Create a string to store the decrypyted message
decrypted_message = ""

# Concatenate the characters using a for loop to get your final decoded message



# Print the message you have decrypted

"""### <u> Problem 3</u>

#### Aliens receive the reply from the scientists. They decode the message and send an encrypted message again. Due to some aberrations because of an existing very massive star, one of the words of their message gets transformed into something gibberish/unreadable. They sent the following message:

* <code> I saw a \<**some gibberish**> please help me soon

#### Scientists were baffled by the presence of such an indecipherable word in the message sent by Aliens. Suddenly they receive another signal from them which contains the gibberish word but this time the letters have been jumbled up. Scientists need to sort the letters of this word in alphabetical order within it to get the actual transmitted word

#### The encoded list of the unknown word is:

```
jumbled_word = ["hugdtck", "tsogbklesrawqcbjplu", "qkisrubskoaitbt", "nslaoetr", "oksinjioaendnjsdqwbh"]
```

"""

# Store the list of jumbled word in a variable 
jumbled_word = ["hugdtck", "tsogbklesrawqcbjplu", "qkisrubskoaitbt", "nslaoetr", "oksinjioaendnjsdqwbh"]

# Create an empty list 
string_length_list = []

# Append the length of each string in the list using a for loop




# Print the above list


# Create another list to store the corresponding characters and add the characters using for loop
chars_in_jumbled_state = []




# Print this list of jumbled characters
print(chars_in_jumbled_state)

# Get the  sorted list
sorted_char_list = 

# Print the sorted list


# Get all the characters in one word. Use join() method on a null string and pass the sorted char list as the argument of this method. Use help(join) to know more about it.
correct_word = 

# Print the complete message
print(f"I saw a {correct_word} please help me soon")

"""## <u> Problem 4</u>

### A perfect number is a positive integer that is equal to the sum of its proper divisors. The smallest perfect number is 6, which is the sum of 1, 2, and 3. Based on a given user input, you need to print whether the input is a perfect number or not. Check on sample inputs such as 28, 128, 200, 496
"""

# Take the user input

perfect_number_candidate = int(input())

# Using a while loop check if a number is a perfect number

"""## <u> Problem 5</u>

### Consider a famous movie line by Liam Neeson. You need to print only those words from this famous line whose length is greater than 3. Also the output words should be unique.You need to take care of the special characters such as ,. Characters such as apostrophe will be considered to be part of the word.
"""

# Liam Neeson's quote
movie_quote = "If you let my daughter go now, that'll be the end of it. I will not look for you, I will not pursue you. But if you don't, I will look for you, I will find you, and I will kill you."

# Remove the characters which are not to be considered. In this case they include characters such as , .



# Print the modified movie quote
print(movie_quote)

# Convert your sentence to a list of words
list_of_words = 


# Using a for loop, print the words whose length is greater than 3
words_we_want = []




# Take only unique words
unique_words = 
print(f"The unique word list is {unique_words} ")

